### ISSUE TITLE
it doesn't work with husky 

### ISSUE THREAD

**Issue by bimaindra** [promet99/cz-emoji-conventional#1]
I'm using this plugin with `commitizen`, `commitlint` and `husky`. 

But it seems this plugin still does not work together with the Husky configuration as they have `commit-msg` hooks to check the commit message -> `pnpm dlx commitlint --edit $1.`  

Got this error 
<img width="600" alt="Screenshot 2024-04-27 at 11 01 01" src="https://github.com/promet99/cz-emoji-conventional/assets/4485008/c29c3379-b1b2-4c15-adf8-4eec32e7633e">

Any idea how to fix it?

**Comment by promet99** [comment]
Hi, 
1. Husky does not seem to be the problem.
2. It seems like commitlint is failing. Which is not quite related to this package.
3. this plugin is interactive. Which means, you are asked to type in the commit msg, "after" `git commit`. Is this how you are using this package?

Try testing commitizen and this package, WITHOUT husky and commitlint.
